feat: add managent api
casbin/k8s-gatekeeper pull request #20
Opened 2022-08-03 11:52 UTC by ComradeProgrammer

feat: add managent api

2022-08-06 14:38 UTC, hsluoyz commented
@ComradeProgrammer plz fix:

![image](https://user-images.githubusercontent.com/3787410/183253542-adb0edec-dd03-4eba-a681-136e7f93561e.png)

2022-08-06 14:38 UTC, hsluoyz commented
@ComradeProgrammer plz fix:

![image](https://user-images.githubusercontent.com/3787410/183253542-adb0edec-dd03-4eba-a681-136e7f93561e.png)

2022-08-20 05:45 UTC, hsluoyz commented
@sagilio

2022-08-20 07:13 UTC, sagilio requested changes
Most LGTM

2022-08-20 07:13 UTC, sagilio commented on pkg/client/internal.go
> +	return strings.Join(tmp, ",")
```suggestion
	return strings.Join(tmp, ", ")
```

2022-08-20 07:13 UTC, sagilio commented on pkg/client/policy.go
> +	return k.AddNamedPolicies("p", [][]string{rule})
It looks like it should call `SetNamedPolicies` func.

2022-09-01 12:11 UTC, hsluoyz commented
@sagilio

2022-09-08 22:00 UTC, sagilio approved these changes
LGTM

2022-09-09 05:14 UTC, merged