feat: implement helm support
casbin/k8s-gatekeeper pull request #22
Opened 2022-08-09 07:09 UTC by ComradeProgrammer

feat: implement helm support

2022-08-09 09:18 UTC, hsluoyz commented
@sagilio

2022-08-17 16:46 UTC, hsluoyz commented
@sagilio

2022-08-28 12:36 UTC, sagilio requested changes

2022-08-28 12:36 UTC, sagilio commented on k8sgatekeeper/values.yaml
> +# Default values for ksauth.
Plz move some user options to here

2022-09-01 08:47 UTC, ComradeProgrammer commented
@sagilio  revisions requested by last meeting has all been implemented

2022-09-01 12:10 UTC, hsluoyz commented
@sagilio plz review

2022-09-12 18:07 UTC, sagilio approved these changes
LGTM

2022-09-12 18:07 UTC, merged